### ISSUE TITLE
scripts/runner.sh  giving errors "sbatch: command not found"

### ISSUE THREAD

**Issue by narayanal** [p-lambda/incontext-learning#4]
scripts/runner.sh  giving errors "sbatch: command not found"

Any pointers on how to get rid of this issue

**Comment by alycialee** [comment]
Do you have slurm installed?

**Comment by narayanal** [comment]
I have installed "slurm", still i get the same error

**Comment by narayanal** [comment]
I have followed the steps mentioned in the quickstart and installed "slurm" also, still getting "sbatch:command not found"

https://github.com/p-lambda/incontext-learning#quickstart

**Comment by sangmichaelxie** [comment]
You can always run the commands locally instead of on slurm by using bash:

Toy example:
```python
sbatch --partition mycluster myjob.sh arg1 arg2 
```
would become 
```
bash myjob.sh arg1 arg2
```
